In [5]:
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.metrics import classification_report,confusion_matrix,plot_confusion_matrix,make_scorer,accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier 
import xgboost as xgb
from sklearn.model_selection import train_test_split, cross_val_predict,cross_val_score,cross_validate
from sklearn.feature_selection import SelectFromModel
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [6]:
import pandas as pd
import numpy as np
from numpy import sort
import time
import datetime
from pandas import Series,DataFrame

In [7]:
import os
os.getcwd()

'C:\\Users\\wang331\\paper 3'

In [9]:
Xy1=pd.read_csv("file name.csv")
Xy2016=Xy1.loc[Xy["year"] ==2016]
Xy0515=Xy1.loc[Xy["year"] !=2016]
Xy_0515=Xy0515.drop(columns=["year"])
Xy_2016=Xy2016.drop(columns=["year"])
y_2016=Xy_2016["above_or_below_limit"].copy()
X_2016=Xy_2016.drop(columns=["above_or_below_limit"]).copy()
Xy11=Xy_0515
y=Xy11["above_or_below_limit"].copy()
X=Xy11.drop(columns=["above_or_below_limit",]).copy()

In [17]:
X=pd.get_dummies(X,columns=['product',"proutgroup","pdg_name_engels","country_of_origin","country_of_analysis","legal_limit"])
X_2016=pd.get_dummies(X_2016,columns=['product',"proutgroup","pdg_name_engels","country_of_origin","country_of_analysis","legal_limit"])
X_2016 = X_2016.reindex(columns = X.columns, fill_value=0)
X.apply(pd.to_numeric)
X_2016.apply(pd.to_numeric)

In [27]:
X_train1, X_test1, y_train1, y_test1= train_test_split(X,y,train_size=0.9,random_state=1,stratify=y)
sum(y_test1),len(y_test1),sum(y),len(y),sum(y_train1),len(y_train1),
X_train, X_test, y_train, y_test= train_test_split(X_train1,y_train1,train_size=0.9,random_state=1,stratify=y_train1)
scaler = StandardScaler()
scaler.fit(X_train) 
X_train_stander = scaler.transform(X_train)
X_test_stander = scaler.transform(X_test)
X_test1_stander = scaler.transform(X_test1)
X_2016_stander = scaler.transform(X_2016)

In [101]:
log_clf = LogisticRegression(random_state=42)#,class_weight="balanced",C=0.00001,penalty='l2',)#{0:0.001,1:0.999},max_iter=1000
log_clf.fit(X_train_stander, y_train)
y_pred = log_clf.predict(X_test_stander)
y_pred_train = log_clf.predict(X_train_stander)
y_pred1 = log_clf.predict(X_test1_stander)
y_pred_2016 = log_clf.predict(X_2016_stander)

print(confusion_matrix(y_test, y_pred),roc_auc_score(y_test, y_pred),custom_loss(y_test, y_pred),custom_losshis(y_test, y_pred),recall_score(y_test, y_pred),accuracy_score(y_test, y_pred),f1_score(y_test, y_pred),precision_score(y_test, y_pred))
print(confusion_matrix(y_train, y_pred_train),roc_auc_score(y_train, y_pred_train),custom_loss(y_train, y_pred_train),custom_losshis(y_train, y_pred_train),recall_score(y_train, y_pred_train),accuracy_score(y_train, y_pred_train),f1_score(y_train, y_pred_train),precision_score(y_train, y_pred_train))
print(confusion_matrix(y_test1, y_pred1),roc_auc_score(y_test1, y_pred1),custom_loss(y_test1, y_pred1),custom_losshis(y_test1, y_pred1),recall_score(y_test1, y_pred1),accuracy_score(y_test1, y_pred1),f1_score(y_test1, y_pred1),precision_score(y_test1, y_pred1))
print(confusion_matrix(y_2016, y_pred_2016),roc_auc_score(y_2016, y_pred_2016),custom_loss(y_2016, y_pred_2016),custom_losshis(y_2016, y_pred_2016),recall_score(y_2016, y_pred_2016),accuracy_score(y_2016, y_pred_2016),f1_score(y_2016, y_pred_2016),precision_score(y_2016, y_pred_2016))

[[606   0]
 [  3   0]] 0.5 68244 66990 0.0 0.9950738916256158 0.0 0.0
[[5445    6]
 [  16   10]] 0.6917573345751662 365728 602470 0.38461538461538464 0.9959832024831112 0.4761904761904762 0.625
[[670   4]
 [  1   2]] 0.8303659742828882 23408 74470 0.6666666666666666 0.9926144756277696 0.4444444444444444 0.3333333333333333
[[369   2]
 [  1   0]] 0.4973045822102426 22968 40920 0.0 0.9919354838709677 0.0 0.0


C:\Users\wang331\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\wang331\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [102]:
result_log = {'AUC_train':[roc_auc_score(y_train, y_pred_train)],"AUC_validation":[roc_auc_score(y_test, y_pred)],'AUC_test':[roc_auc_score(y_test1, y_pred1)],'AUC_2016':[roc_auc_score(y_2016, y_pred_2016)],                                                                                                          
              'Recall_train':[recall_score(y_train, y_pred_train)],"Recall_validation":[recall_score(y_test, y_pred)],'Recall_test':[recall_score(y_test1, y_pred1)],'Recall_2016':[recall_score(y_2016, y_pred_2016)],                                                                                                               
              'Precision_train':[precision_score(y_train, y_pred_train)],"Precision_validation":[precision_score(y_test, y_pred)],'Precision_test':[precision_score(y_test1, y_pred1)],'Precision_2016':[precision_score(y_2016, y_pred_2016)],                                                                                                         
              'Accuracy_train':[accuracy_score(y_train, y_pred_train)],"Accuracy_validation":[accuracy_score(y_test, y_pred)],'Accuracy_test':[accuracy_score(y_test1, y_pred1)],'Accuracy_2016':[accuracy_score(y_2016, y_pred_2016)],                                                                                                     
             'F1_train':[f1_score(y_train, y_pred_train)],"F1_validation":[f1_score(y_test, y_pred)],'F1_test':[f1_score(y_test1, y_pred1)],'F1_2016':[f1_score(y_2016, y_pred_2016)],
          'Custom_train':[custom_loss(y_train, y_pred_train)],"Custom_validation":[custom_loss(y_test, y_pred)], 'Custom_test':[custom_loss(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],'Customhis_train':[custom_losshis(y_train, y_pred_train)],"Customhis_validation":[custom_losshis(y_test, y_pred)], 'Custom_test':[custom_losshis(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],                                                                                                          
        'Confusion_matrix_train':[confusion_matrix(y_train, y_pred_train).flatten()],'Confusion_matrix_test':[confusion_matrix(y_test, y_pred).flatten()],'Confusion_matrix_fianl':[confusion_matrix(y_test1, y_pred1).flatten()],'Confusion_matrix_2016':[confusion_matrix(y_2016, y_pred_2016).flatten()]}
result_log = DataFrame(result_log)

C:\Users\wang331\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


AUC_train  AUC_validation  AUC_test  AUC_2016  Recall_train  \
0   0.691757             0.5  0.830366  0.497305      0.384615   

   Recall_validation  Recall_test  Recall_2016  Precision_train  \
0                0.0     0.666667          0.0            0.625   

   Precision_validation  ...  Custom_train  Custom_validation  Custom_test  \
0                   0.0  ...        365728              68244        74470   

   Custom_2016  Customhis_train  Customhis_validation  Confusion_matrix_train  \
0        22968           602470                 66990       [5445, 6, 16, 10]   

   Confusion_matrix_test  Confusion_matrix_fianl  Confusion_matrix_2016  
0         [606, 0, 3, 0]          [670, 4, 1, 2]         [369, 2, 1, 0]  

[1 rows x 30 columns]

In [90]:
sgd_svm=SGDClassifier(random_state=42,loss='hinge')#,loss='hinge', n_iter_no_change=3,validation_fraction=0.1,class_weight="balanced",early_stopping=True,max_iter=1000, tol=1e-3)
#CV
sgd_svm.fit(X_train_stander, y_train)
y_pred = sgd_svm.predict(X_test_stander)
y_pred_train = sgd_svm.predict(X_train_stander)
y_pred1 = sgd_svm.predict(X_test1_stander)
#y_pred_2015 = sgd_svm.predict(X_2015_stander)
y_pred_2016 = sgd_svm.predict(X_2016_stander)

print(confusion_matrix(y_test, y_pred),roc_auc_score(y_test, y_pred),custom_loss(y_test, y_pred),recall_score(y_test, y_pred),accuracy_score(y_test, y_pred),f1_score(y_test, y_pred),precision_score(y_test, y_pred))
print(confusion_matrix(y_train, y_pred_train),roc_auc_score(y_train, y_pred_train),custom_loss(y_train, y_pred_train),recall_score(y_train, y_pred_train),accuracy_score(y_train, y_pred_train),f1_score(y_train, y_pred_train),precision_score(y_train, y_pred_train))
print(confusion_matrix(y_test1, y_pred1),roc_auc_score(y_test1, y_pred1),custom_loss(y_test1, y_pred1),recall_score(y_test1, y_pred1),accuracy_score(y_test1, y_pred1),f1_score(y_test1, y_pred1),precision_score(y_test1, y_pred1))
#print(confusion_matrix(y_2015, y_pred_2015),roc_auc_score(y_2015, y_pred_2015),custom_loss(y_2015, y_pred_2015),recall_score(y_2015, y_pred_2015),accuracy_score(y_2015, y_pred_2015),f1_score(y_2015, y_pred_2015),precision_score(y_2015, y_pred_2015))
print(confusion_matrix(y_2016, y_pred_2016),roc_auc_score(y_2016, y_pred_2016),custom_loss(y_2016, y_pred_2016),
      recall_score(y_2016, y_pred_2016),accuracy_score(y_2016, y_pred_2016),f1_score(y_2016, y_pred_2016),precision_score(y_2016, y_pred_2016))

[[606   0]
 [  2   1]] 0.6666666666666666 45606 0.3333333333333333 0.9967159277504105 0.5 1.0
[[5443    8]
 [  19    7]] 0.6338815743053497 433862 0.2692307692307692 0.9950702939565456 0.3414634146341463 0.4666666666666667
[[671   3]
 [  2   1]] 0.6644411473788329 45936 0.3333333333333333 0.9926144756277696 0.28571428571428575 0.25
[[369   2]
 [  1   0]] 0.4973045822102426 22968 0.0 0.9919354838709677 0.0 0.0


In [89]:
result_svm = {'AUC_train':[roc_auc_score(y_train, y_pred_train)],"AUC_validation":[roc_auc_score(y_test, y_pred)],'AUC_test':[roc_auc_score(y_test1, y_pred1)],'AUC_2016':[roc_auc_score(y_2016, y_pred_2016)],                                                                                                          
              'Recall_train':[recall_score(y_train, y_pred_train)],"Recall_validation":[recall_score(y_test, y_pred)],'Recall_test':[recall_score(y_test1, y_pred1)],'Recall_2016':[recall_score(y_2016, y_pred_2016)],                                                                                                               
              'Precision_train':[precision_score(y_train, y_pred_train)],"Precision_validation":[precision_score(y_test, y_pred)],'Precision_test':[precision_score(y_test1, y_pred1)],'Precision_2016':[precision_score(y_2016, y_pred_2016)],                                                                                                         
              'Accuracy_train':[accuracy_score(y_train, y_pred_train)],"Accuracy_validation":[accuracy_score(y_test, y_pred)],'Accuracy_test':[accuracy_score(y_test1, y_pred1)],'Accuracy_2016':[accuracy_score(y_2016, y_pred_2016)],                                                                                                     
             'F1_train':[f1_score(y_train, y_pred_train)],"F1_validation":[f1_score(y_test, y_pred)],'F1_test':[f1_score(y_test1, y_pred1)],'F1_2016':[f1_score(y_2016, y_pred_2016)],
          'Custom_train':[custom_loss(y_train, y_pred_train)],"Custom_validation":[custom_loss(y_test, y_pred)], 'Custom_test':[custom_loss(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],'Customhis_train':[custom_losshis(y_train, y_pred_train)],"Customhis_validation":[custom_losshis(y_test, y_pred)], 'Custom_test':[custom_losshis(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],                                                                                                          
        'Confusion_matrix_train':[confusion_matrix(y_train, y_pred_train).flatten()],'Confusion_matrix_test':[confusion_matrix(y_test, y_pred).flatten()],'Confusion_matrix_fianl':[confusion_matrix(y_test1, y_pred1).flatten()],'Confusion_matrix_2016':[confusion_matrix(y_2016, y_pred_2016).flatten()]}
result_svm = DataFrame(result_svm)

AUC_train  AUC_validation  AUC_test  AUC_2016  Recall_train  \
0   0.633882        0.666667  0.664441  0.497305      0.269231   

   Recall_validation  Recall_test  Recall_2016  Precision_train  \
0           0.333333     0.333333          0.0         0.466667   

   Precision_validation  ...  Custom_train  Custom_validation  Custom_test  \
0                   1.0  ...        433862              45606        74470   

   Custom_2016  Customhis_train  Customhis_validation  Confusion_matrix_train  \
0        22968           602470                 66990        [5443, 8, 19, 7]   

   Confusion_matrix_test  Confusion_matrix_fianl  Confusion_matrix_2016  
0         [606, 0, 2, 1]          [671, 3, 2, 1]         [369, 2, 1, 0]  

[1 rows x 30 columns]

In [47]:
dt_clf = DecisionTreeClassifier(random_state=42)#,class_weight="balanced",max_depth=10,min_samples_leaf=3)
dt_clf.fit(X_train_stander, y_train)
y_pred = dt_clf.predict(X_test_stander)
y_pred_train = dt_clf.predict(X_train_stander)
y_pred1 = dt_clf.predict(X_test1_stander)
y_pred_2016 = dt_clf.predict(X_2016_stander)

print(confusion_matrix(y_test, y_pred),roc_auc_score(y_test, y_pred),custom_loss(y_test, y_pred),recall_score(y_test, y_pred),accuracy_score(y_test, y_pred),f1_score(y_test, y_pred),precision_score(y_test, y_pred))
print(confusion_matrix(y_train, y_pred_train),roc_auc_score(y_train, y_pred_train),custom_loss(y_train, y_pred_train),recall_score(y_train, y_pred_train),accuracy_score(y_train, y_pred_train),f1_score(y_train, y_pred_train),precision_score(y_train, y_pred_train))
print(confusion_matrix(y_test1, y_pred1),roc_auc_score(y_test1, y_pred1),custom_loss(y_test1, y_pred1),recall_score(y_test1, y_pred1),accuracy_score(y_test1, y_pred1),f1_score(y_test1, y_pred1),precision_score(y_test1, y_pred1))
print(confusion_matrix(y_2016, y_pred_2016),roc_auc_score(y_2016, y_pred_2016),custom_loss(y_2016, y_pred_2016),recall_score(y_2016, y_pred_2016),accuracy_score(y_2016, y_pred_2016),f1_score(y_2016, y_pred_2016),precision_score(y_2016, y_pred_2016))
print(custom_losshis(y_2016, y_pred_2016))

[[425   1]
 [  3   0]] 0.4988262910798122 68354 0.0 0.9906759906759907 0.0 0.0
[[3831    1]
 [   6   20]] 0.8844849044483699 138798 0.7692307692307693 0.9981855883877657 0.8510638297872339 0.9523809523809523
[[471   3]
 [  1   2]] 0.8301687763713079 23298 0.6666666666666666 0.9916142557651991 0.5 0.4
[[232   6]
 [  1   0]] 0.48739495798319327 23408 0.0 0.9707112970711297 0.0 0.0
26290


In [48]:
dt_clf = DecisionTreeClassifier(random_state=42)#,class_weight="balanced",max_depth=10,min_samples_leaf=3)
dt_clf.fit(X_train_stander, y_train)
y_pred = dt_clf.predict(X_test_stander)
y_pred_train = dt_clf.predict(X_train_stander)
y_pred1 = dt_clf.predict(X_test1_stander)
y_pred_2016 = dt_clf.predict(X_2016_stander)

print(confusion_matrix(y_test, y_pred),roc_auc_score(y_test, y_pred),custom_loss(y_test, y_pred),recall_score(y_test, y_pred),accuracy_score(y_test, y_pred),f1_score(y_test, y_pred),precision_score(y_test, y_pred))
print(confusion_matrix(y_train, y_pred_train),roc_auc_score(y_train, y_pred_train),custom_loss(y_train, y_pred_train),recall_score(y_train, y_pred_train),accuracy_score(y_train, y_pred_train),f1_score(y_train, y_pred_train),precision_score(y_train, y_pred_train))
print(confusion_matrix(y_test1, y_pred1),roc_auc_score(y_test1, y_pred1),custom_loss(y_test1, y_pred1),recall_score(y_test1, y_pred1),accuracy_score(y_test1, y_pred1),f1_score(y_test1, y_pred1),precision_score(y_test1, y_pred1))
print(confusion_matrix(y_2016, y_pred_2016),roc_auc_score(y_2016, y_pred_2016),custom_loss(y_2016, y_pred_2016),recall_score(y_2016, y_pred_2016),accuracy_score(y_2016, y_pred_2016),f1_score(y_2016, y_pred_2016),precision_score(y_2016, y_pred_2016))
print(custom_losshis(y_2016, y_pred_2016))

[[425   1]
 [  3   0]] 0.4988262910798122 68354 0.0 0.9906759906759907 0.0 0.0
[[3831    1]
 [   6   20]] 0.8844849044483699 138798 0.7692307692307693 0.9981855883877657 0.8510638297872339 0.9523809523809523
[[471   3]
 [  1   2]] 0.8301687763713079 23298 0.6666666666666666 0.9916142557651991 0.5 0.4
[[232   6]
 [  1   0]] 0.48739495798319327 23408 0.0 0.9707112970711297 0.0 0.0
26290


In [93]:
result_dt = {'AUC_train':[roc_auc_score(y_train, y_pred_train)],"AUC_validation":[roc_auc_score(y_test, y_pred)],'AUC_test':[roc_auc_score(y_test1, y_pred1)],'AUC_2016':[roc_auc_score(y_2016, y_pred_2016)],                                                                                                          
              'Recall_train':[recall_score(y_train, y_pred_train)],"Recall_validation":[recall_score(y_test, y_pred)],'Recall_test':[recall_score(y_test1, y_pred1)],'Recall_2016':[recall_score(y_2016, y_pred_2016)],                                                                                                               
              'Precision_train':[precision_score(y_train, y_pred_train)],"Precision_validation":[precision_score(y_test, y_pred)],'Precision_test':[precision_score(y_test1, y_pred1)],'Precision_2016':[precision_score(y_2016, y_pred_2016)],                                                                                                         
              'Accuracy_train':[accuracy_score(y_train, y_pred_train)],"Accuracy_validation":[accuracy_score(y_test, y_pred)],'Accuracy_test':[accuracy_score(y_test1, y_pred1)],'Accuracy_2016':[accuracy_score(y_2016, y_pred_2016)],                                                                                                     
             'F1_train':[f1_score(y_train, y_pred_train)],"F1_validation":[f1_score(y_test, y_pred)],'F1_test':[f1_score(y_test1, y_pred1)],'F1_2016':[f1_score(y_2016, y_pred_2016)],
          'Custom_train':[custom_loss(y_train, y_pred_train)],"Custom_validation":[custom_loss(y_test, y_pred)], 'Custom_test':[custom_loss(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],'Customhis_train':[custom_losshis(y_train, y_pred_train)],"Customhis_validation":[custom_losshis(y_test, y_pred)], 'Custom_test':[custom_losshis(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],                                                                                                          
        'Confusion_matrix_train':[confusion_matrix(y_train, y_pred_train).flatten()],'Confusion_matrix_test':[confusion_matrix(y_test, y_pred).flatten()],'Confusion_matrix_fianl':[confusion_matrix(y_test1, y_pred1).flatten()],'Confusion_matrix_2016':[confusion_matrix(y_2016, y_pred_2016).flatten()]}
result_dt = DataFrame(result_dt)

AUC_train  AUC_validation  AUC_test  AUC_2016  Recall_train  \
0    0.92271         0.49835  0.997774  0.494609      0.846154   

   Recall_validation  Recall_test  Recall_2016  Precision_train  \
0                0.0          1.0          0.0         0.846154   

   Precision_validation  ...  Custom_train  Custom_validation  Custom_test  \
0                   0.0  ...         93852              68464        74470   

   Custom_2016  Customhis_train  Customhis_validation  Confusion_matrix_train  \
0        23188           602470                 66990        [5447, 4, 4, 22]   

   Confusion_matrix_test  Confusion_matrix_fianl  Confusion_matrix_2016  
0         [604, 2, 3, 0]          [671, 3, 0, 3]         [367, 4, 1, 0]  

[1 rows x 30 columns]

In [49]:
xgb_clf = xgb.XGBClassifier(random_state=42)#,objective="binary:logistic",gamma=1.0, learning_rate=0.1, max_depth=4,reg_lambda=10.0,scale_pos_weight=559,subsample=0.5)#subsample=0.9, scale_pos_weight=1000,max_depth=4)#,objective="binary:logistic",gamma=1.0, learning_rate=0.1, max_depth=4,reg_lambda=10.0,scale_pos_weight=5,subsample=0.5)#subsample=0.9, scale_pos_weight=1000,max_depth=4
xgb_clf.fit(X_train_stander, y_train)#,eval_set=eval_set, eval_metric=['error',"logloss","aucpr","auc",],early_stopping_rounds=20)
y_pred = xgb_clf.predict(X_test_stander)
y_pred_train = xgb_clf.predict(X_train_stander)
y_pred1 = xgb_clf.predict(X_test1_stander)
y_pred_2016 = xgb_clf.predict(X_2016_stander)

print(confusion_matrix(y_test, y_pred),roc_auc_score(y_test, y_pred),custom_loss(y_test, y_pred),recall_score(y_test, y_pred),accuracy_score(y_test, y_pred),f1_score(y_test, y_pred),precision_score(y_test, y_pred))
print(confusion_matrix(y_train, y_pred_train),roc_auc_score(y_train, y_pred_train),custom_loss(y_train, y_pred_train),recall_score(y_train, y_pred_train),accuracy_score(y_train, y_pred_train),f1_score(y_train, y_pred_train),precision_score(y_train, y_pred_train))
print(confusion_matrix(y_test1, y_pred1),roc_auc_score(y_test1, y_pred1),custom_loss(y_test1, y_pred1),recall_score(y_test1, y_pred1),accuracy_score(y_test1, y_pred1),f1_score(y_test1, y_pred1),precision_score(y_test1, y_pred1))
print(confusion_matrix(y_2016, y_pred_2016),roc_auc_score(y_2016, y_pred_2016),custom_loss(y_2016, y_pred_2016),
      recall_score(y_2016, y_pred_2016),accuracy_score(y_2016, y_pred_2016),f1_score(y_2016, y_pred_2016),precision_score(y_2016, y_pred_2016))


C:\Users\wang331\AppData\Local\Continuum\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:59:14] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[425   1]
 [  2   1]] 0.6654929577464788 45716 0.3333333333333333 0.993006993006993 0.4 0.5
[[3829    3]
 [   4   22]] 0.9226854825758792 93742 0.8461538461538461 0.9981855883877657 0.8627450980392156 0.88
[[470   4]
 [  1   2]] 0.8291139240506329 23408 0.6666666666666666 0.989517819706499 0.4444444444444444 0.3333333333333333
[[236   2]
 [  1   0]] 0.4957983193277311 22968 0.0 0.9874476987447699 0.0 0.0


In [96]:
result_xgb = {'AUC_train':[roc_auc_score(y_train, y_pred_train)],"AUC_validation":[roc_auc_score(y_test, y_pred)],'AUC_test':[roc_auc_score(y_test1, y_pred1)],'AUC_2016':[roc_auc_score(y_2016, y_pred_2016)],                                                                                                          
              'Recall_train':[recall_score(y_train, y_pred_train)],"Recall_validation":[recall_score(y_test, y_pred)],'Recall_test':[recall_score(y_test1, y_pred1)],'Recall_2016':[recall_score(y_2016, y_pred_2016)],                                                                                                               
              'Precision_train':[precision_score(y_train, y_pred_train)],"Precision_validation":[precision_score(y_test, y_pred)],'Precision_test':[precision_score(y_test1, y_pred1)],'Precision_2016':[precision_score(y_2016, y_pred_2016)],                                                                                                         
              'Accuracy_train':[accuracy_score(y_train, y_pred_train)],"Accuracy_validation":[accuracy_score(y_test, y_pred)],'Accuracy_test':[accuracy_score(y_test1, y_pred1)],'Accuracy_2016':[accuracy_score(y_2016, y_pred_2016)],                                                                                                     
             'F1_train':[f1_score(y_train, y_pred_train)],"F1_validation":[f1_score(y_test, y_pred)],'F1_test':[f1_score(y_test1, y_pred1)],'F1_2016':[f1_score(y_2016, y_pred_2016)],
          'Custom_train':[custom_loss(y_train, y_pred_train)],"Custom_validation":[custom_loss(y_test, y_pred)], 'Custom_test':[custom_loss(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],'Customhis_train':[custom_losshis(y_train, y_pred_train)],"Customhis_validation":[custom_losshis(y_test, y_pred)], 'Custom_test':[custom_losshis(y_test1, y_pred1)],'Custom_2016':[custom_loss(y_2016, y_pred_2016)],                                                                                                          
        'Confusion_matrix_train':[confusion_matrix(y_train, y_pred_train).flatten()],'Confusion_matrix_test':[confusion_matrix(y_test, y_pred).flatten()],'Confusion_matrix_fianl':[confusion_matrix(y_test1, y_pred1).flatten()],'Confusion_matrix_2016':[confusion_matrix(y_2016, y_pred_2016).flatten()]}
result_xgb = DataFrame(result_xgb)

AUC_train  AUC_validation  AUC_test  AUC_2016  Recall_train  \
0   0.826556        0.664191   0.83185  0.993261      0.653846   

   Recall_validation  Recall_test  Recall_2016  Precision_train  \
0           0.333333     0.666667          1.0         0.809524   

   Precision_validation  ...  Custom_train  Custom_validation  Custom_test  \
0                  0.25  ...        207042              45936        74470   

   Custom_2016  Customhis_train  Customhis_validation  Confusion_matrix_train  \
0          660           602470                 66990        [5447, 4, 9, 17]   

   Confusion_matrix_test  Confusion_matrix_fianl  Confusion_matrix_2016  
0         [603, 3, 2, 1]          [672, 2, 1, 2]         [366, 5, 0, 1]  

[1 rows x 30 columns]

In [103]:
result_tuning= pd.concat([result_log, result_svm, result_dt,result_xgb],names=['Model'],keys=['result_log', 'result_svm', 'result_dt',"result_xgb"])
result_tuning.to_csv("result_untuning_afb1.csv")
result_tuning

AUC_train  AUC_validation  AUC_test  AUC_2016  Recall_train  \
Model                                                                       
result_log 0   0.691757        0.500000  0.830366  0.497305      0.384615   
result_svm 0   0.633882        0.666667  0.664441  0.497305      0.269231   
result_dt  0   0.922710        0.498350  0.997774  0.494609      0.846154   
result_xgb 0   0.826556        0.664191  0.831850  0.993261      0.653846   

              Recall_validation  Recall_test  Recall_2016  Precision_train  \
Model                                                                        
result_log 0           0.000000     0.666667          0.0         0.625000   
result_svm 0           0.333333     0.333333          0.0         0.466667   
result_dt  0           0.000000     1.000000          0.0         0.846154   
result_xgb 0           0.333333     0.666667          1.0         0.809524   

              Precision_validation  ...  Custom_train  Custom_validation  \
Model                               ...                                    
result_log 0                  0.00  ...        365728              68244   
result_svm 0                  1.00  ...        433862              45606   
result_dt  0                  0.00  ...         93852              68464   
result_xgb 0                  0.25  ...        207042              45936   

              Custom_test  Custom_2016  Customhis_train  Customhis_validation  \
Model                                                                           
result_log 0        74470        22968           602470                 66990   
result_svm 0        74470        22968           602470                 66990   
result_dt  0        74470        23188           602470                 66990   
result_xgb 0        74470          660           602470                 66990   

              Confusion_matrix_train  Confusion_matrix_test  \
Model                                                         
result_log 0       [5445, 6, 16, 10]         [606, 0, 3, 0]   
result_svm 0        [5443, 8, 19, 7]         [606, 0, 2, 1]   
result_dt  0        [5447, 4, 4, 22]         [604, 2, 3, 0]   
result_xgb 0        [5447, 4, 9, 17]         [603, 3, 2, 1]   

              Confusion_matrix_fianl  Confusion_matrix_2016  
Model                                                        
result_log 0          [670, 4, 1, 2]         [369, 2, 1, 0]  
result_svm 0          [671, 3, 2, 1]         [369, 2, 1, 0]  
result_dt  0          [671, 3, 0, 3]         [367, 4, 1, 0]  
result_xgb 0          [672, 2, 1, 2]         [366, 5, 0, 1]  

[4 rows x 30 columns]